/**
 * Única fuente de verdad para strings de permisos en el frontend.
 * Espejo de backend/src/common/constants/permissions.enum.ts
 *
 * Usar en: hasPermission(), RoleGuard, PrivateRoute, guardas de UI.
 */
export const PERMS = {
  // ── Permisos de módulo — sistema RBAC modular (On/Off por módulo) ──────
  MODULO_CATALOGO:    'MODULO_CATALOGO',
  MODULO_ALMACEN:     'MODULO_ALMACEN',
  MODULO_INVENTARIO:  'MODULO_INVENTARIO',
  MODULO_DESPACHOS:   'MODULO_DESPACHOS',
  MODULO_TERMINAL:    'MODULO_TERMINAL',
  MODULO_PROVEEDORES: 'MODULO_PROVEEDORES',
  MODULO_FINANZAS:    'MODULO_FINANZAS',
  MODULO_REPORTES:    'MODULO_REPORTES',
  MODULO_RRHH:        'MODULO_RRHH',
  MODULO_USUARIOS:    'MODULO_USUARIOS',
  MODULO_SEGURIDAD:   'MODULO_SEGURIDAD',

  // ── Permisos granulares heredados ──────────────────────────────────────
  CATEGORIA_VER:      'ACCESO_CATEGORIA_VER',
  CATEGORIA_CREAR:    'ACCESO_CATEGORIA_CREAR',
  CATEGORIA_EDITAR:   'ACCESO_CATEGORIA_EDITAR',
  CATEGORIA_ELIMINAR: 'ACCESO_CATEGORIA_ELIMINAR',
  CATEGORIA_IMPRIMIR: 'ACCESO_CATEGORIA_IMPRIMIR',

  PRODUCTO_VER:       'ACCESO_PRODUCTO_VER',
  PRODUCTO_CREAR:     'ACCESO_PRODUCTO_CREAR',
  PRODUCTO_EDITAR:    'ACCESO_PRODUCTO_EDITAR',
  PRODUCTO_ELIMINAR:  'ACCESO_PRODUCTO_ELIMINAR',
  PRODUCTO_IMPRIMIR:  'ACCESO_PRODUCTO_IMPRIMIR',

  ALMACEN_VER:        'ACCESO_ALMACEN_VER',
  ALMACEN_CREAR:      'ACCESO_ALMACEN_CREAR',
  ALMACEN_EDITAR:     'ACCESO_ALMACEN_EDITAR',
  ALMACEN_ELIMINAR:   'ACCESO_ALMACEN_ELIMINAR',
  ALMACEN_IMPRIMIR:   'ACCESO_ALMACEN_IMPRIMIR',

  INVENTARIO_VER:       'ACCESO_INVENTARIO_VER',
  INVENTARIO_CREAR:     'ACCESO_INVENTARIO_CREAR',
  INVENTARIO_EDITAR:    'ACCESO_INVENTARIO_EDITAR',
  INVENTARIO_ELIMINAR:  'ACCESO_INVENTARIO_ELIMINAR',
  INVENTARIO_IMPRIMIR:  'ACCESO_INVENTARIO_IMPRIMIR',

  MONITOREO_GPS_VER:       'ACCESO_MONITOREO_GPS_VER',
  MONITOREO_GPS_CREAR:     'ACCESO_MONITOREO_GPS_CREAR',
  MONITOREO_GPS_EDITAR:    'ACCESO_MONITOREO_GPS_EDITAR',
  MONITOREO_GPS_ELIMINAR:  'ACCESO_MONITOREO_GPS_ELIMINAR',
  MONITOREO_GPS_IMPRIMIR:  'ACCESO_MONITOREO_GPS_IMPRIMIR',

  TERMINAL_VEHICULAR_VER:       'ACCESO_TERMINAL_VEHICULAR_VER',
  TERMINAL_VEHICULAR_CREAR:     'ACCESO_TERMINAL_VEHICULAR_CREAR',
  TERMINAL_VEHICULAR_EDITAR:    'ACCESO_TERMINAL_VEHICULAR_EDITAR',
  TERMINAL_VEHICULAR_ELIMINAR:  'ACCESO_TERMINAL_VEHICULAR_ELIMINAR',
  TERMINAL_VEHICULAR_IMPRIMIR:  'ACCESO_TERMINAL_VEHICULAR_IMPRIMIR',

  CONTABILIDAD_VER:       'ACCESO_CONTABILIDAD_VER',
  CONTABILIDAD_CREAR:     'ACCESO_CONTABILIDAD_CREAR',
  CONTABILIDAD_EDITAR:    'ACCESO_CONTABILIDAD_EDITAR',
  CONTABILIDAD_ELIMINAR:  'ACCESO_CONTABILIDAD_ELIMINAR',
  CONTABILIDAD_IMPRIMIR:  'ACCESO_CONTABILIDAD_IMPRIMIR',

  PROVEEDOR_VER:       'ACCESO_PROVEEDOR_VER',
  PROVEEDOR_CREAR:     'ACCESO_PROVEEDOR_CREAR',
  PROVEEDOR_EDITAR:    'ACCESO_PROVEEDOR_EDITAR',
  PROVEEDOR_ELIMINAR:  'ACCESO_PROVEEDOR_ELIMINAR',
  PROVEEDOR_IMPRIMIR:  'ACCESO_PROVEEDOR_IMPRIMIR',

  VENTA_VER:       'ACCESO_VENTA_VER',
  VENTA_CREAR:     'ACCESO_VENTA_CREAR',
  VENTA_EDITAR:    'ACCESO_VENTA_EDITAR',
  VENTA_ELIMINAR:  'ACCESO_VENTA_ELIMINAR',
  VENTA_IMPRIMIR:  'ACCESO_VENTA_IMPRIMIR',

  CLIENTE_VER:       'ACCESO_CLIENTE_VER',
  CLIENTE_CREAR:     'ACCESO_CLIENTE_CREAR',
  CLIENTE_EDITAR:    'ACCESO_CLIENTE_EDITAR',
  CLIENTE_ELIMINAR:  'ACCESO_CLIENTE_ELIMINAR',
  CLIENTE_IMPRIMIR:  'ACCESO_CLIENTE_IMPRIMIR',

  GESTION_RRHH_VER:       'ACCESO_GESTION_RRHH_VER',
  GESTION_RRHH_CREAR:     'ACCESO_GESTION_RRHH_CREAR',
  GESTION_RRHH_EDITAR:    'ACCESO_GESTION_RRHH_EDITAR',
  GESTION_RRHH_ELIMINAR:  'ACCESO_GESTION_RRHH_ELIMINAR',
  GESTION_RRHH_IMPRIMIR:  'ACCESO_GESTION_RRHH_IMPRIMIR',

  USUARIO_VER:       'ACCESO_USUARIO_VER',
  USUARIO_CREAR:     'ACCESO_USUARIO_CREAR',
  USUARIO_EDITAR:    'ACCESO_USUARIO_EDITAR',
  USUARIO_ELIMINAR:  'ACCESO_USUARIO_ELIMINAR',
  USUARIO_IMPRIMIR:  'ACCESO_USUARIO_IMPRIMIR',

  ROL_VER:       'ACCESO_ROL_VER',
  ROL_CREAR:     'ACCESO_ROL_CREAR',
  ROL_EDITAR:    'ACCESO_ROL_EDITAR',
  ROL_ELIMINAR:  'ACCESO_ROL_ELIMINAR',
  ROL_IMPRIMIR:  'ACCESO_ROL_IMPRIMIR',
} as const;

export type PermKey = keyof typeof PERMS;
export type PermValue = typeof PERMS[PermKey];
